### ISSUE TITLE
Error: Not authorized for action "read" for Rundeck System ACLs 

### ISSUE THREAD

**Issue by hmalinov** [rundeck/rundeck-cli#101]
I want to use "rd" for creating projects and ACL policies, but whatever I try it gives me an autorization error. Here is my setup 

Version 1.0.14

export RD_URL=http://localhost:4440/api/19
export RD_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXX

# rd system acls list --outformat %name
Error: Not authorized for action "read" for Rundeck System ACLs 
[code: api.error.item.unauthorized; APIv19]

org.rundeck.client.api.AuthorizationFailed: Authorization failed: 403 Forbidden
	at org.rundeck.client.util.Client.checkError(Client.java:117)
	at org.rundeck.client.util.Client.checkError(Client.java:94)
	at org.rundeck.client.tool.commands.AppCommand.apiCall(AppCommand.java:56)
	at org.rundeck.client.tool.commands.AppCommand.apiCall(AppCommand.java:47)
	at org.rundeck.client.tool.commands.system.ACLs.list(ACLs.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simplifyops.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:778)
	at com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:492)
	at com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:359)
	at com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:492)
	at com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:359)
	at com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:492)
	at com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:359)
	at com.simplifyops.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:322)
	at org.rundeck.client.tool.Main.main(Main.java:56)

# User: rundeck_admin:xxxxxxx,user,admin,api_token_group

# admin.aclpolicy

~~~{.yaml}
description: Admin project level access control. Applies to resources within a specific project.
context:
  project: '.*' # all projects
for:
  resource:
    - equals:
        kind: job
      allow: [create] # allow create jobs
    - equals:
        kind: node
      allow: [read,create,update,refresh] # allow refresh node sources
    - equals:
        kind: event
      allow: [read,create] # allow read/create events
  adhoc:
    - allow: [read,run,runAs,kill,killAs] # allow running/killing adhoc jobs
  job:
    - allow: [create,read,update,delete,run,runAs,kill,killAs] # allow create/read/write/delete/run/kill of all jobs
  node:
    - allow: [read,run] # allow read/run for nodes
by:
  group: [admin,it]

---

description: Admin Application level access control, applies to creating/deleting projects, admin of user profiles, viewing projects and reading system information.
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: project
      allow: [create] # allow create of projects
    - equals:
        kind: system
      allow: [read,enable_executions,disable_executions,admin] # allow read of system info, enable/disable all executions
    - equals:
        kind: system_acl
      allow: [read,create,update,delete,admin] # allow modifying system ACL files
    - equals:
        kind: user
      allow: [admin] # allow modify user profiles
  project:
    - match:
        name: '.*'
      allow: [read,import,export,configure,delete,admin] # allow full access of all projects or use 'admin'
  project_acl:
    - match:
        name: '.*'
      allow: [read,create,update,delete,admin] # allow modifying project-specific ACL files
  storage:
    - allow: [read,create,update,delete] # allow access for /ssh-key/* storage content

by:
  group: [admin,it]

~~~

I would appreciate a hint of what am I missing in my configuration. 
Note that using the RD_USER and RD_PASSWORD works fine.

**Comment by gschueler** [comment]
you need to allow `admin` action for `system_acl` type

~~~{.yaml}
description: 'Allow system ACL admin access'
context:
  application: 'rundeck'
for:
  system_acl:
    - allow: [admin]
by:
  group: [admin]
~~~
