### ISSUE TITLE
Timeout on a rd jobs command

### ISSUE THREAD

**Issue by Navet94** [rundeck/rundeck-cli#104]
Hi everyone.

I want to save my jobs with the rd jobs command but when I launch it, it tells me a timeout error : 

[rundeck@ORDSIT2 rundeck]$ rd jobs list -f /etc/rundeck/backup/jobs/blabla.xml -p My_Project
java.net.SocketTimeoutException: timeout
        at okio.Okio$3.newTimeoutException(Okio.java:210)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:288)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:242)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
        at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
        at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:53)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at org.rundeck.client.util.FormAuthInterceptor.authenticate(FormAuthInterceptor.java:76)
        at org.rundeck.client.util.FormAuthInterceptor.intercept(FormAuthInterceptor.java:47)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at org.rundeck.client.util.StaticHeaderInterceptor.intercept(StaticHeaderInterceptor.java:22)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
        at okhttp3.RealCall.execute(RealCall.java:60)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
        at org.rundeck.client.util.Client.checkError(Client.java:75)
        at org.rundeck.client.tool.commands.Jobs.list(Jobs.java:187)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.simplifyops.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:778)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:492)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:359)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:492)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:359)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:322)
        at org.rundeck.client.tool.Main.main(Main.java:46)
Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.read(SocketInputStream.java:204)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at okio.Okio$2.read(Okio.java:138)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
        ... 41 more

The funny thing, I have another server, build identically except the version of rundeck and its works on the other server.

Last thing, if i try to just list my job, it works :

[rundeck@ORDSIT2 rundeck]$ rd jobs list -p My_Project
# 10 Jobs in project My_Project
622a5f24-973d-43d6-996b-4f977a21e5b9 
da4ddf91-681f-4b23-9762-18a7ab77f086 
cb5c0310-7ad5-4735-841a-efd2339b5fa7 
479fecb3-c3f8-437b-9f2f-388f89a8b156 
350be2a7-f049-41aa-a51c-64df5e0c299b 
b73aedcd-a141-49fb-a3c0-148e106e9927 
b8d37371-c0a2-47ed-a259-0283935198e5 
e13c1b9b-02ad-464d-b8bf-e79f56a019d4 
9d2fb2aa-2b1b-4460-bc73-3c4e7172bddf 
a14174aa-29b4-434a-9f5a-b4b43c2e3037 

Thanks in advance to help me.

Best regards.

**Comment by Navet94** [comment]
I find the problem, i forget to create a rd.conf.

I did it and add RD_HTTP_TIMEOUT.

Works great.
