### ISSUE TITLE
"Not a valid base URL" Error Using RD 2.6.11, API v18

### ISSUE THREAD

**Issue by niall-munnelly** [rundeck/rundeck-cli#138]
Let's say I'm listing jobs in my "Release_Management" project, `rd jobs list -p Release_Management.` Whether I let Rundeck auto-negotiate with the downgrade option or hard-code the API version in my rd.conf, I get the same results:

`Exception in thread "main" java.lang.IllegalArgumentException: Not a valid base URL: RD_URL=https://my.rundeck.server:4443/api/18
        at org.rundeck.client.RundeckClient$Builder.validateBaseUrl(RundeckClient.java:263)
        at org.rundeck.client.RundeckClient$Builder.baseUrl(RundeckClient.java:115)
        at org.rundeck.client.tool.Main.createClient(Main.java:297)
        at org.rundeck.client.tool.Main.createClient(Main.java:281)
        at org.rundeck.client.tool.Main$Rd.getClient(Main.java:217)
        at org.rundeck.client.tool.Main$Rd.getClient(Main.java:186)
        at org.rundeck.client.tool.commands.AppCommand.apiCallDowngradable(AppCommand.java:118)
        at org.rundeck.client.tool.commands.AppCommand.apiCall(AppCommand.java:61)
        at org.rundeck.client.tool.commands.Jobs.list(Jobs.java:244)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.simplifyops.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:801)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:504)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:371)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:504)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:371)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:332)
        at org.rundeck.client.tool.Main.main(Main.java:69)
`

I can still list the project's jobs with a cURL request successfully, though:

```
curl -k -L -X GET --header "Accept: text/html, text/xml, application/xhtml+xml, application/xml;q=0.9, */*" --header "X-Rundeck-Auth-Token:[token]" https://my.rundeck.server:4443/api/18/project/Release_Management/jobs
<?xml version="1.0" encoding="UTF-8"?><jobs count="6">

<snip/>

```

What's the earliest supported API version?

**Comment by niall-munnelly** [comment]
rd v1.0.22, btw.

**Comment by gschueler** [comment]
what is the value of `echo $RD_URL` ? or the contents of your `rd.conf` file?

That error message indicates that your base url is set to the literal string: `RD_URL=https://my.rundeck.server:4443/api/18`

api v18 is supported

**Comment by niall-munnelly** [comment]
@gschueler Oh, I get you. Sorry, I was doing the bash parameter substitution stuff wrong. Once I corrected that, it worked as advertised. Awesome. Thanks!
