### ISSUE TITLE
Error during deletion of executions

### ISSUE THREAD

**Issue by majkinetor** [rundeck/rundeck-cli#141]
It still deleted all.

```
4 succeeded 2017-11-29T08:35:00+0100 2017-11-29T08:35:11+0100 https://testwsd.mfin.trezor.rs:4443/project/CRF/execution/show/4 job e990daad-79a2-4e4e-a269-9e87cc29e2fc /Jafin 2 Crf
3 succeeded 2017-11-29T08:30:00+0100 2017-11-29T08:30:11+0100 https://testwsd.mfin.trezor.rs:4443/project/CRF/execution/show/3 job e990daad-79a2-4e4e-a269-9e87cc29e2fc /Jafin 2 Crf
2 succeeded 2017-11-29T08:25:00+0100 2017-11-29T08:25:11+0100 https://testwsd.mfin.trezor.rs:4443/project/CRF/execution/show/2 job e990daad-79a2-4e4e-a269-9e87cc29e2fc /Jafin 2 Crf
1 succeeded 2017-11-29T08:20:00+0100 2017-11-29T08:20:12+0100 https://testwsd.mfin.trezor.rs:4443/project/CRF/execution/show/1 job e990daad-79a2-4e4e-a269-9e87cc29e2fc /Jafin 2 Crf
# End of results.
Really delete 5521 executions? (y/N) y
   java.net.SocketTimeoutException: timeout
        at okio.Okio$3.newTimeoutException(Okio.java:210)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:288)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:242)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
        at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
        at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:53)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at org.rundeck.client.util.StaticHeaderInterceptor.intercept(StaticHeaderInterceptor.java:38)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at org.rundeck.client.util.FormAuthInterceptor.intercept(FormAuthInterceptor.java:62)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
        at okhttp3.RealCall.execute(RealCall.java:60)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
        at org.rundeck.client.util.Client.checkErrorDowngradable(Client.java:138)
        at org.rundeck.client.util.Client.apiCallDowngradable(Client.java:578)
        at org.rundeck.client.tool.commands.AppCommand.apiCallDowngradable(AppCommand.java:118)
        at org.rundeck.client.tool.commands.AppCommand.apiCall(AppCommand.java:61)
        at org.rundeck.client.tool.commands.Executions.deletebulk(Executions.java:513)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.simplifyops.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:801)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:504)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:371)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:504)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:371)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:332)
        at org.rundeck.client.tool.Main.main(Main.java:69)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at okio.Okio$2.read(Okio.java:138)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
        ... 43 more
```

**Comment by gschueler** [comment]
It probably takes a long time.  you can change the timeout, see https://rundeck.github.io/rundeck-cli/configuration/#httpconnect-timeout

**Comment by majkinetor** [comment]
Yeah, that helped. Perhaps a better message should be returned here. 

Thanks.

**Comment by am312** [comment]
I'm still seeing this error.  I have not changed any timeouts from the default.
