### ISSUE TITLE
rd keys list NullPointerException when no keys are present

### ISSUE THREAD

**Issue by xirixiz** [rundeck/rundeck-cli#177]
"rd keys list" gives a NullPointerException when no keys are present in Rundeck. 
It would be nice to receive a message that currently no resources are configured, or something like that.

**Comment by gschueler** [comment]
can you paste the stacktrace?

**Comment by xirixiz** [comment]
```
Exception in thread "main" java.lang.NullPointerException
        at org.rundeck.client.tool.commands.Keys.lambda$list$0(Keys.java:92)
        at org.rundeck.client.util.Client.apiCallDowngradable(Client.java:578)
        at org.rundeck.client.tool.commands.AppCommand.apiCallDowngradable(AppCommand.java:118)
        at org.rundeck.client.tool.commands.AppCommand.apiCall(AppCommand.java:61)
        at org.rundeck.client.tool.commands.Keys.list(Keys.java:92)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.rundeck.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:820)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:523)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:390)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:523)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:390)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:351)
        at org.rundeck.client.tool.Main.main(Main.java:69)
```
