### ISSUE TITLE
All Rundeck commands are not working

### ISSUE THREAD

**Issue by rahsaanpage-nbcuni** [rundeck/rundeck-cli#182]
Hello,

Im having issues with my rundeck cli `rc-*` commands are not working all of a sudden.

i use to be able to run `/usr/bin/rd projects list` to list all projects so i can create backup and upload it to s3.

all variable set as required to use commands:

export RD_URL=
export RD_TOKEN=

please advise?

**Comment by gschueler** [comment]
what is the error message?

**Comment by rahsaanpage-nbcuni** [comment]
@gschueler there is no error msg returned, is there a log file i can look at?

**Comment by gschueler** [comment]
try using `RD_DEBUG=1` env var, or `RD_DEBUG=3` for full http request info

**Comment by rahsaanpage-nbcuni** [comment]
@gschueler i tried the debug option 1 and 3, where does the verbose goes? is it suppose to output on my screen or some log file?

-bash-4.2$ export RD_DEBUG=3
-bash-4.2$ rd list projects

**Comment by rahsaanpage-nbcuni** [comment]
i ran the following command `rd system info` here is my out

-bash-4.2$ rd system info
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO: --> GET http://localhost:4440/api/21/system/info http/1.1
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO: Accept: application/json
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO: X-Rundeck-Auth-Token: JotXVQ53iioZxobvdxH2PoPE8E0uoPNd
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO: User-Agent: rundeck-cli/1.0.27
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO: Host: localhost:4440
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO: Connection: Keep-Alive
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO: Accept-Encoding: gzip
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO: --> END GET
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO: <-- 400 Bad Request http://localhost:4440/api/21/system/info (7ms)
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO: Set-Cookie: JSESSIONID=12q6cvilr5ie7cvegxnyvwb6d;Path=/
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO: Expires: Thu, 01 Jan 1970 00:00:00 GMT
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO: Content-Type: application/json;charset=UTF-8
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO: X-Rundeck-API-Version: 18
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO: Transfer-Encoding: chunked
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO: Server: Jetty(7.6.0.v20120127)
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO:
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO: {"error":true,"apiversion":18,"errorCode":"api.error.api-version.unsupported","message":"Unsupported API Version \"21\". API Request: /api/21/system/info. Reason: Current version: 18"}
Jun 01, 2018 6:08:44 PM okhttp3.internal.platform.Platform log
INFO: <-- END HTTP (184-byte body)

**Comment by rahsaanpage-nbcuni** [comment]
-bash-4.2$ rpm -qa|grep -i rundeck
rundeck-cli-1.0.27-1.noarch

**Comment by rahsaanpage-nbcuni** [comment]
ok, i forced API version as you suggested and now i see an unauthorized error with my token

-bash-4.2$ export RD_URL=http://localhost:4440/api/18
-bash-4.2$ rd system acls list
Jun 01, 2018 6:39:17 PM okhttp3.internal.platform.Platform log
INFO: --> GET http://localhost:4440/api/18/system/acl/ http/1.1
Jun 01, 2018 6:39:17 PM okhttp3.internal.platform.Platform log
INFO: Accept: application/json
Jun 01, 2018 6:39:17 PM okhttp3.internal.platform.Platform log
INFO: X-Rundeck-Auth-Token: JotXVQ53iioZxobvdxH2PoPE8E0uoPNd
Jun 01, 2018 6:39:17 PM okhttp3.internal.platform.Platform log
INFO: User-Agent: rundeck-cli/1.0.27
Jun 01, 2018 6:39:17 PM okhttp3.internal.platform.Platform log
INFO: Host: localhost:4440
Jun 01, 2018 6:39:17 PM okhttp3.internal.platform.Platform log
INFO: Connection: Keep-Alive
Jun 01, 2018 6:39:17 PM okhttp3.internal.platform.Platform log
INFO: Accept-Encoding: gzip
Jun 01, 2018 6:39:17 PM okhttp3.internal.platform.Platform log
INFO: --> END GET
Jun 01, 2018 6:39:17 PM okhttp3.internal.platform.Platform log
INFO: <-- 403 Forbidden http://localhost:4440/api/18/system/acl/ (21ms)
Jun 01, 2018 6:39:17 PM okhttp3.internal.platform.Platform log
INFO: Set-Cookie: JSESSIONID=r60ujoulhox714z0vb9lkgkee;Path=/
Jun 01, 2018 6:39:17 PM okhttp3.internal.platform.Platform log
INFO: Expires: Thu, 01 Jan 1970 00:00:00 GMT
Jun 01, 2018 6:39:17 PM okhttp3.internal.platform.Platform log
INFO: Content-Type: application/json;charset=UTF-8
Jun 01, 2018 6:39:17 PM okhttp3.internal.platform.Platform log
INFO: Transfer-Encoding: chunked
Jun 01, 2018 6:39:17 PM okhttp3.internal.platform.Platform log
INFO: Server: Jetty(7.6.0.v20120127)
Jun 01, 2018 6:39:17 PM okhttp3.internal.platform.Platform log
INFO:
Jun 01, 2018 6:39:17 PM okhttp3.internal.platform.Platform log
INFO: {"error":true,"apiversion":18,"errorCode":"unauthorized","message":"(Token:JotXV****) is not authorized for: /api/18/system/acl/"}
Jun 01, 2018 6:39:17 PM okhttp3.internal.platform.Platform log
INFO: <-- END HTTP (130-byte body)
-bash-4.2$ rd projects list
Jun 01, 2018 6:39:32 PM okhttp3.internal.platform.Platform log
INFO: --> GET http://localhost:4440/api/18/projects http/1.1
Jun 01, 2018 6:39:32 PM okhttp3.internal.platform.Platform log
INFO: Accept: application/json
Jun 01, 2018 6:39:32 PM okhttp3.internal.platform.Platform log
INFO: X-Rundeck-Auth-Token: JotXVQ5***********
Jun 01, 2018 6:39:32 PM okhttp3.internal.platform.Platform log
INFO: User-Agent: rundeck-cli/1.0.27
Jun 01, 2018 6:39:32 PM okhttp3.internal.platform.Platform log
INFO: Host: localhost:4440
Jun 01, 2018 6:39:32 PM okhttp3.internal.platform.Platform log
INFO: Connection: Keep-Alive
Jun 01, 2018 6:39:32 PM okhttp3.internal.platform.Platform log
INFO: Accept-Encoding: gzip
Jun 01, 2018 6:39:32 PM okhttp3.internal.platform.Platform log
INFO: --> END GET
Jun 01, 2018 6:39:32 PM okhttp3.internal.platform.Platform log
INFO: <-- 403 Forbidden http://localhost:4440/api/18/projects (26ms)
Jun 01, 2018 6:39:32 PM okhttp3.internal.platform.Platform log
INFO: Set-Cookie: JSESSIONID=gk4stmnomuyc1p1rp3j6glfs6;Path=/
Jun 01, 2018 6:39:32 PM okhttp3.internal.platform.Platform log
INFO: Expires: Thu, 01 Jan 1970 00:00:00 GMT
Jun 01, 2018 6:39:32 PM okhttp3.internal.platform.Platform log
INFO: Content-Type: application/json;charset=UTF-8
Jun 01, 2018 6:39:32 PM okhttp3.internal.platform.Platform log
INFO: Transfer-Encoding: chunked
Jun 01, 2018 6:39:32 PM okhttp3.internal.platform.Platform log
INFO: Server: Jetty(7.6.0.v20120127)
Jun 01, 2018 6:39:32 PM okhttp3.internal.platform.Platform log
INFO:
Jun 01, 2018 6:39:32 PM okhttp3.internal.platform.Platform log
INFO: {"error":true,"apiversion":18,"errorCode":"unauthorized","message":"(Token:JotXV****) is not authorized for: /api/18/projects"}
Jun 01, 2018 6:39:32 PM okhttp3.internal.platform.Platform log
INFO: <-- END HTTP (127-byte body)

**Comment by gschueler** [comment]
were you able to resolve this issue by updating your access control, or renewing your token?

**Comment by mwvinzi** [comment]
`
rd projects list
java.net.ConnectException: Failed to connect to localhost/127.0.0.1:4440
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:189)
	at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at org.rundeck.client.util.StaticHeaderInterceptor.intercept(StaticHeaderInterceptor.java:38)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at org.rundeck.client.util.StaticHeaderInterceptor.intercept(StaticHeaderInterceptor.java:38)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.execute(RealCall.java:60)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at org.rundeck.client.util.Client.checkErrorDowngradable(Client.java:138)
	at org.rundeck.client.util.Client.apiCallDowngradable(Client.java:578)
	at org.rundeck.client.tool.commands.AppCommand.apiCallDowngradable(AppCommand.java:119)
	at org.rundeck.client.tool.commands.AppCommand.apiCall(AppCommand.java:62)
	at org.rundeck.client.tool.commands.Projects.list(Projects.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.rundeck.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:820)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:523)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:390)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:523)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:390)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:351)
	at org.rundeck.client.tool.Main.main(Main.java:61)

`
