### ISSUE TITLE
timeout when load thousands of jobs

### ISSUE THREAD

**Issue by changsijay** [rundeck/rundeck-cli#194]
Hi I have an joblist `all.xml`, which contains around 5000 jobs in the file.
when I run `rd jobs load -d update -f all.xml -F xml -p demo -r`

it exception error as below

```
java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:210)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:288)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:242)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:53)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at org.rundeck.client.util.StaticHeaderInterceptor.intercept(StaticHeaderInterceptor.java:38)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at org.rundeck.client.util.FormAuthInterceptor.intercept(FormAuthInterceptor.java:62)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.execute(RealCall.java:60)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at org.rundeck.client.util.Client.checkErrorDowngradable(Client.java:138)
	at org.rundeck.client.util.Client.apiCallDowngradable(Client.java:578)
	at org.rundeck.client.tool.commands.AppCommand.apiCallDowngradable(AppCommand.java:119)
	at org.rundeck.client.tool.commands.AppCommand.apiCall(AppCommand.java:62)
	at org.rundeck.client.tool.commands.Jobs.load(Jobs.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.rundeck.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:820)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:523)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:390)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:523)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:390)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:351)
	at org.rundeck.client.tool.Main.main(Main.java:61)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
	... 43 more
```

**Comment by sjrd218** [comment]
@changsijay Have you tried setting the environment variable`RD_HTTP_TIMEOUT` to a longer period? The default is 30 seconds. You could set it to 5 min like:  `export RD_HTTP_TIMEOUT=300` and see if that works for your import.

**Comment by changsijay** [comment]
cool, after set `RD_HTTP_TIMEOUT=300` it works fine.
