### ISSUE TITLE
I tried to create project using rd command line, throwing 403 unauth error

### ISSUE THREAD

**Issue by gangadhar01a** [rundeck/rundeck-cli#203]
I have tried 2 methods to create project through rd command line tool

Method 1) using auth token

This resulted the following error message 

"Error: Not authorized for action "create" for Rundeck Project
[code: api.error.item.unauthorized; APIv24]
Authorization failed: 403 Forbidden"

Method 2) Using my user account and password 
"Exception in thread "main" org.rundeck.client.api.LoginFailed: Password Authentication failed for: gangadhar.pulipelli
	at org.rundeck.client.util.FormAuthInterceptor.authenticate(FormAuthInterceptor.java:86)
	at org.rundeck.client.util.FormAuthInterceptor.intercept(FormAuthInterceptor.java:59)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)"

I prefer to use method 1 so that we can automate the entire process through chef in order to create and maintain projects. Unfortunately, it looks like the api token required to have elevated privileges in order to perform these action and I am having difficult time to find corresponding documentation to  perform these.

**Comment by gangadhar01a** [comment]
Updating the "apitoken.aclpolicy" fixed the issue
