### ISSUE TITLE
Getting the error: Unsupported major.minor version 52.0 when trying to run rd

### ISSUE THREAD

**Issue by benruset** [rundeck/rundeck-cli#214]
I just installed rundeck-cli from the Rundeck yum repo. My system has Java 8 installed, however when I try to run rd I get:

`# rd
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/rundeck/client/tool/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)` 

The default version of Java on the system is 8

`# java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)`

**Comment by ProTip** [comment]
Hi @benruset ,

It looks like the startup script uses `JAVA_HOME` to locate the jvm if set, otherwise it falls back on looking for java in the path. Do you have another JDK version installed and set to `JAVA_HOME` by chance?

Thanks!

**Comment by gschueler** [comment]
I will close the issue. If you still have this problem, please re-open this issue.

**Comment by benruset** [comment]
Sorry, this sort of fell off my radar.

Just wanted to make a note of how I fixed this under Amazon Linux in case someone runs into the same problem. I'm using Amazon Linux. It turns out that the alternatives symlink for "javac" was set to a different version than what "java" was set to. Running "/usr/sbin/alternatives --config javac" and setting it to Java 1.8 fixed my problem.

**Comment by PatelAshish11** [comment]
The version number shown describes the version of the JRE the class file is compatible with.

The reported major numbers are:

Java SE 13 = 57,
Java SE 12 = 56,
Java SE 11 = 55,
Java SE 10 = 54,
Java SE 9 = 53,
Java SE 8 = 52,
Java SE 7 = 51,
Java SE 6.0 = 50,
Java SE 5.0 = 49,
JDK 1.4 = 48,
JDK 1.3 = 47,
JDK 1.2 = 46,
JDK 1.1 = 45

Full source [here](https://icetutor.com/question/how-to-fix-java-lang-unsupportedclassversionerror-unsupported-major-minor-version/)
