### ISSUE TITLE
Connection time out version 1.1.3

### ISSUE THREAD

**Issue by atuvida** [rundeck/rundeck-cli#234]
Hi,

I'm getting the following error whenever I try to do any commands using the new rundeck-cli

java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.java:124)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:187)
        at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:196)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:132)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:101)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at org.rundeck.client.util.StaticHeaderInterceptor.intercept(StaticHeaderInterceptor.java:38)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at org.rundeck.client.util.FormAuthInterceptor.authenticate(FormAuthInterceptor.java:69)
        at org.rundeck.client.util.FormAuthInterceptor.intercept(FormAuthInterceptor.java:59)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
        at okhttp3.RealCall.execute(RealCall.java:63)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
        at org.rundeck.client.util.Client.checkErrorDowngradable(Client.java:138)
        at org.rundeck.client.util.Client.apiCallDowngradable(Client.java:578)
        at org.rundeck.client.tool.commands.AppCommand.apiCallDowngradable(AppCommand.java:119)
        at org.rundeck.client.tool.commands.AppCommand.apiCall(AppCommand.java:62)
        at org.rundeck.client.tool.commands.Projects.list(Projects.java:69)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.rundeck.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:820)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:523)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:390)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:523)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:390)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:351)
        at org.rundeck.client.tool.Main.main(Main.java:66)

I installed the cli using rpm in centos and created .rd/rd.conf file under ~/ as a root user.

and here's my config:

export RD_URL=http://[public ip]:4440/api/31

#export RD_URL=http://[public ip]:4440 tried.. same error
#export RD_URL=http://[public ip]:4440/ tried.. same error
#export RD_URL=http://[public ip]::4440/rundeck tried.. same error
#export RD_URL=http://[private ip]:4440 tried.. same error

export RD_USER=myuser
export RD_PASSWORD=mypassword

export RD_DEBUG=1

# 60 second timeout
export RD_HTTP_TIMEOUT=60

**Comment by atuvida** [comment]
this is okay now.. I set all my config ips to private (rd.conf , framework.properties and rundeck-config.groovy).. probably has something to do with my server's firewall.. will have to check further.. but for now it's working with that setup and I'll leave it as is for now..

**Comment by CarterSheehan** [comment]
Any more info here?
