### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by arifrahman4u** [rundeck/rundeck-cli#25]
Hi ,

when executing status.sh getting below error.

[root@rknode01 status]# ./status.sh
Exception in thread "main" java.lang.NullPointerException
        at org.rundeck.client.Rundeck.client(Rundeck.java:164)
        at org.rundeck.client.Rundeck.client(Rundeck.java:65)
        at org.rundeck.client.tool.App.createClient(App.java:114)
        at org.rundeck.client.tool.App.tool(App.java:64)
        at org.rundeck.client.tool.App.main(App.java:29)
Exception in thread "main" java.lang.NullPointerException
        at org.rundeck.client.Rundeck.client(Rundeck.java:164)
        at org.rundeck.client.Rundeck.client(Rundeck.java:65)
        at org.rundeck.client.tool.App.createClient(App.java:114)
        at org.rundeck.client.tool.App.tool(App.java:64)
        at org.rundeck.client.tool.App.main(App.java:29)
Exception in thread "main" java.lang.NullPointerException
        at org.rundeck.client.Rundeck.client(Rundeck.java:164)
        at org.rundeck.client.Rundeck.client(Rundeck.java:65)
        at org.rundeck.client.tool.App.createClient(App.java:114)
        at org.rundeck.client.tool.App.tool(App.java:64)
        at org.rundeck.client.tool.App.main(App.java:29)
[root@rknode01 status]#

we are useing latet version 25 .

our configuration.

[root@rknode01 status]# java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)
OpenJDK 64-Bit Server VM (build 25.111-b15, mixed mode)
[root@rknode01 status]#

**Comment by gschueler** [comment]
verify your `RUNDECK_URL` environment variable is set to a valid URL.

I will add a check in case it cannot be parsed
