### ISSUE TITLE
SSL exception

### ISSUE THREAD

**Issue by vinc3nt** [rundeck/rundeck-cli#26]
That's what I have got trying to use it via ssl.

```
$ java -jar rundeck-cli-0.1.24-all.jar jobs list -p Universal
javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
	at sun.security.ssl.ClientHandshaker.handshakeAlert(ClientHandshaker.java:1441)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2016)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:241)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:198)
	at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at org.rundeck.client.util.FormAuthInterceptor.intercept(FormAuthInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.execute(RealCall.java:60)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at org.rundeck.client.util.Client.checkError(Client.java:75)
	at org.rundeck.client.tool.commands.Jobs.list(Jobs.java:210)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simplifyops.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:694)
	at com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:427)
	at com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:306)
	at com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:427)
	at com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:306)
	at com.simplifyops.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:269)
	at org.rundeck.client.tool.App.main(App.java:29)
	Suppressed: javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
		... 43 more
```

Looking at [this page](http://stackoverflow.com/questions/32713522/ssl-javax-net-ssl-sslprotocolexception-handshake-alert-unrecognized-name-accep) it looks like that the issue might be related to a wrong SNI

however SNI seems to be configured on the server
```
$ openssl s_client -servername rundeck.example.com -tlsextdebug -connect rundeck.example.com:443 2>/dev/null | grep "server name"
TLS server extension "server name" (id=0), len=0
```

do you have any suggestion? or is there a way to work it around?

**Comment by gschueler** [comment]
did you try disabling the SNI extension? `-Djsse.enableSNIExtension=false` 

For `rd` set this env var:

    RD_OPT="-Djsse.enableSNIExtension=false"

**Comment by vinc3nt** [comment]
it seems to be the same:
```
$ export RD_OPT="-Djsse.enableSNIExtension=false"
$ java -jar rundeck-cli-0.1.24-all.jar jobs list -p Universal
javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
        at sun.security.ssl.ClientHandshaker.handshakeAlert(ClientHandshaker.java:1441)
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2016)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:241)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:198)
        at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at org.rundeck.client.util.FormAuthInterceptor.intercept(FormAuthInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
        at okhttp3.RealCall.execute(RealCall.java:60)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
        at org.rundeck.client.util.Client.checkError(Client.java:75)
        at org.rundeck.client.tool.commands.Jobs.list(Jobs.java:210)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.simplifyops.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:694)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:427)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:306)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:427)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:306)
        at com.simplifyops.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:269)
        at org.rundeck.client.tool.App.main(App.java:29)
        Suppressed: javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
                ... 43 more
```

**Comment by gschueler** [comment]
hmm, is there any public-facing https site that i can test agains to reproduce this?

or a dockerfile?

**Comment by gschueler** [comment]
closing, let me know if this is still an issue and if there is a way i can reproduce it
