### ISSUE TITLE
START_ARRAY

### ISSUE THREAD

**Issue by cpoule23** [rundeck/rundeck-cli#298]
Hi all,

I'm looking to user rundeck cli , I van use it, for exemple : 

root@fd7e8b4bda71:/# rd projects list
# 2 Projects:
myproject
test

but when I try to create a new project : 

root@fd7e8b4bda71:/# rd projects create -p test2
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `org.rundeck.client.api.model.ProjectItem` out of START_ARRAY token
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1139)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1093)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1461)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203)
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
        at org.rundeck.client.util.Client.checkErrorDowngradable(Client.java:138)
        at org.rundeck.client.util.Client.apiCallDowngradable(Client.java:578)
        at org.rundeck.client.tool.commands.AppCommand.apiCallDowngradable(AppCommand.java:103)
        at org.rundeck.client.tool.commands.AppCommand.apiCall(AppCommand.java:74)
        at org.rundeck.client.tool.commands.Projects.create(Projects.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.rundeck.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:1023)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:624)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:476)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:624)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:476)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:433)
        at org.rundeck.client.tool.Main.main(Main.java:71)
root@fd7e8b4bda71:/# 

I am on kubernetes on GKE, v1.14.10-gke.34

rundeck version : Rundeck 3.0.12-20190114. Try to latest one, undeck 3.2.5-20200403 but same problem.

Do you have an idea please ?

**Comment by gschueler** [comment]
can you export `RD_DEBUG=3` and try it again?
