### ISSUE TITLE
rd jobs load JAXB-API has not been found

### ISSUE THREAD

**Issue by bendermIBM** [rundeck/rundeck-cli#341]
Hey Rundeck community! Building a CICD mechanism for updating rundeck jobs based off of code stored in GitHub... I installed the cli tool on Ubuntu Focal with openjdk-11-jre and ran into an issue which I think revolves around the JAXB-API class not being found.

**NOTE :** Possible solution realized in v1.3.9 of the rdcli. See [comment below](https://github.com/rundeck/rundeck-cli/issues/341#issuecomment-860605552) for more info

```
rd jobs load -f tmp
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/var/lib/rundeck-cli/rd-cli-tool-shadow-1.3.4/lib/rundeck-cli-1.3.4-all.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.IllegalArgumentException: Unable to create converter for class org.rundeck.client.api.model.ImportResult
    for method RundeckApi.loadJobs
	at retrofit2.Utils.methodError(Utils.java:54)
	at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:126)
	at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:85)
	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
	at com.sun.proxy.$Proxy9.loadJobs(Unknown Source)
	at org.rundeck.client.tool.commands.Jobs.lambda$load$2(Jobs.java:174)
	at org.rundeck.client.util.Client.apiCallDowngradable(Client.java:606)
	at org.rundeck.client.tool.commands.AppCommand.apiCallDowngradable(AppCommand.java:103)
	at org.rundeck.client.tool.commands.AppCommand.apiCall(AppCommand.java:74)
	at org.rundeck.client.tool.commands.Jobs.load(Jobs.java:174)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.rundeck.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:1030)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:619)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:471)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:619)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:471)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:428)
	at org.rundeck.client.tool.Main.main(Main.java:74)
Caused by: java.lang.IllegalArgumentException: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at retrofit2.converter.jaxb.JaxbConverterFactory.contextForType(JaxbConverterFactory.java:81)
	at retrofit2.converter.jaxb.JaxbConverterFactory.responseBodyConverter(JaxbConverterFactory.java:72)
	at org.rundeck.client.util.QualifiedTypeConverterFactory.responseBodyConverter(QualifiedTypeConverterFactory.java:58)
	at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:362)
	at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:345)
	at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:124)
	... 21 more
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:278)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:421)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
	at retrofit2.converter.jaxb.JaxbConverterFactory.contextForType(JaxbConverterFactory.java:79)
	... 26 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:122)
	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:155)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:276)
	... 30 more
```

Downgrading java to openjdk-8-jre fixes the issue FYI

**Comment by fyro2k** [comment]
Someone is going to fix it with Java 11? 👍

**Comment by suslikas** [comment]
Same error

```
Debian 10
openjdk-11-jre-headless:amd64 11.0.9.1+1-1~deb10u2
rd 1.3.4
```

**Comment by EugenMayer** [comment]
Building from source does actually fix it

**Comment by bendermIBM** [comment]
> Building from source does actually fix it

I wonder if when building it from source it correctly configures the path for the JAXB-API. So looks like an issue with how it's distributed and maybe default libraries available for J11?

**Comment by EugenMayer** [comment]
Most probably rather a fatjar vs non-fat jar issue in this case, but to be honest, i did not even look at it. It is not as important for me here

**Comment by Vebryn** [comment]
Up

**Comment by gvirtuoso** [comment]
Same here:

```
rundeck@e571d2667423:~/jobs$ java --version
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)

rundeck@e571d2667423:~/jobs$ rd --version
1.3.4
```

**Comment by fstehle** [comment]
> I have downgrade to jdk 8 as @bendermIBM said and everything back to work properly.
> 
> Official Dockerfile (Rundeck:3.3.8):
> https://github.com/rundeck/rundeck/blob/main/docker/ubuntu-base/Dockerfile#L31
> 
> My Dockerfile:
> 
> ```
> ...
> RUN sudo apt-get update \
>     && sudo apt-get remove --purge openjdk-11-jdk-headless -y \
>     && sudo apt-get install -y openjdk-8-jdk
> 
> ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
> RUN export JAVA_HOME
> ....
> ```

Works like a charm!

**Comment by Crypter** [comment]
I'm also experiencing this issue with Java 11, downgrading to Java 8 is not an option for me.
Is someone working on it? What can be done to fix it?

**Comment by dj-wasabi** [comment]
I don't see any documentation on how to build from source, how do I build this? I have this issue with the deb file, zip file and the *-all.jar file and each time it gives me the same error message. And I am using the official rundeck/rundeck:3.3.11 Docker image, in which I found it personally a bit weird that we get this issue.

**Comment by Crypter** [comment]
> [#341 (comment)](https://github.com/rundeck/rundeck-cli/issues/341#issuecomment-742100294)

Let me fix my reply: What can be done to fix it for everyone in the public release? Compiling it every time there's an update doesn't sound fun.

**Comment by bendermIBM** [comment]
> > [#341 (comment)](https://github.com/rundeck/rundeck-cli/issues/341#issuecomment-742100294)
> 
> Let me fix my reply: What can be done to fix it for everyone in the public release? Compiling it every time there's an update doesn't sound fun.
> 
> Edit: Can we switch to building with openjdk11 without breaking a lot of stuff?

Needs someone to step up and take a look at the binary compile process to figure out how to include this missing library in the generation. I'm not versed with how the Rundeck community supports PRs, but I imagine they would be open to anybody working on this issue.

Have any contributors acknowledged this issue so far? cc @gschueler

**Comment by EugenMayer** [comment]
Expecting this to have been fixed by https://github.com/rundeck/rundeck-cli/blob/HEAD/CHANGELOG.md#135

**Comment by gschueler** [comment]
I haven't looked at this issue specifically.

Also FYI I am working on restoring the packaging and release workflows right now (due to bintray), so 1.3.5 and probably the next few "releases" will be me testing out the new release workflow. I will update the changelog with complete info once it is stablized.

**Comment by Crypter** [comment]
Release 1.3.9 fixed this issue for me.

There are still some Warnings, but the Exception is not there anymore and I can work with this.

Thanks!

**Comment by bendermIBM** [comment]
> Release 1.3.9 fixed this issue for me.
> 
> There are still some Warnings, but the Exception is not there anymore and I can work with this.
> 
> Thanks!

Cool! I will test again in my environment and then I think we can close this out 😄 

Thanks Devs for you're continued support!

**Comment by gschueler** [comment]
@bendermIBM closed this issue, lmk if it has not been fixed
