### ISSUE TITLE
rd projects archives: java.io.EOFException

### ISSUE THREAD

**Issue by rmueck** [rundeck/rundeck-cli#343]
Hi,
i am facing an issue when i try to export projects. 
The project exists and has jobs.

Versions:
rundeck-3.1.2.20190927-1.noarch
rundeck-cli-1.3.4-1.noarch
java-1.8.0-openjdk

`# rd projects archives export -f PROJECT.zip -p PROJECT`

Output:
```
# Export Archive for project: PROJECT
# Contents: null
# Begin asynchronous request...
java.io.EOFException: \n not found: limit=0 content=…
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:240)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:224)
        at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.java:489)
        at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.java:471)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
        at okio.RealBufferedSource.readAll(RealBufferedSource.java:176)
        at retrofit2.Utils.buffer(Utils.java:323)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:229)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
        at org.rundeck.client.util.Client.checkError(Client.java:132)
        at org.rundeck.client.util.Client.apiCall(Client.java:574)
        at org.rundeck.client.tool.commands.projects.Archives.loopStatus(Archives.java:252)
        at org.rundeck.client.tool.commands.projects.Archives.export(Archives.java:230)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.rundeck.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:1030)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:619)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:471)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:619)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:471)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:619)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:471)
        at org.rundeck.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:428)
        at org.rundeck.client.tool.Main.main(Main.java:74)
```

Any help is higly appreciated!

**Comment by rmueck** [comment]
The cause was a full filesystem in /tmp/rundeck. One project had a large amount of executions (cleanup was disabled). The resulting export was not cleaned after the error.
