### ISSUE TITLE
rundeck cli ( v1.4.0 ) - command: job load failed with error - JAXB-API has not been found on module path or classpath.

### ISSUE THREAD

**Issue by fidalcastro** [rundeck/rundeck-cli#433]
Hey Rundeck Team, running cli command `job load` using `rundeck cli jar` of version v1.4.2 with Rundeck server  v4.2.1-20220511 fails with java runtime error i.e `JAXB-API has not be found on module path or classpath`. Similar Issue: https://github.com/rundeck/rundeck-cli/issues/341 has been reported and closed.

I've tried using the same command with cli version 1.3.11 which works fine.

**Environment:**

| | |
| --- | --- |
| Operating system | Ubuntu 18.04 & Ubuntu 20.04 |
| Rundeck version | rundeck/rundeck:4.2.1-20220511 (using docker) |
| Rundeck CLI version | v1.4.2  - [rundeck-cli-1.4.2-all.jar](https://github.com/rundeck/rundeck-cli/releases/download/v1.4.2/rundeck-cli-1.4.2-all.jar)|
| Java Version | openjdk 11.0.14.1 2022-02-08  |

Running commands inside rundeck container

```shell
❯ docker exec -it affectionate_taussig bash
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

rundeck@6bfe7aeae911:~$ 
rundeck@6bfe7aeae911:~$ export RD_USER=admin
rundeck@6bfe7aeae911:~$ export RD_PASSWORD=password
rundeck@6bfe7aeae911:~$ export RD_URL=http://0.0.0.0:4440
rundeck@6bfe7aeae911:~$ 
rundeck@6bfe7aeae911:~$ java -jar rundeck-cli-1.4.2-all.jar projects create --project DEMO
# Created project: 
# 	DEMO
rundeck@6bfe7aeae911:~$ 
rundeck@6bfe7aeae911:~$ 
rundeck@6bfe7aeae911:~$ ll
total 262376
drwxrwxr-x 1 rundeck root      4096 May 12 18:16 ./
drwxr-xr-x 1 root    root      4096 Apr  6 00:18 ../
-rw------- 1 rundeck root       937 May 12 18:22 .bash_history
-rw-r--r-- 1 rundeck root       220 Apr  6 00:18 .bash_logout
-rw-r--r-- 1 rundeck root      3771 Apr  6 00:18 .bashrc
-rw-r--r-- 1 rundeck root       807 Apr  6 00:18 .profile
-rw-r--r-- 1 rundeck root         0 May 12 17:50 derby.log
drwxr-xr-x 3 rundeck root      4096 May 11 17:53 docker-lib/
drwxrwxr-x 1 rundeck root      4096 May 12 17:50 etc/
drwxrwxr-x 1 rundeck root      4096 May 12 17:50 libext/
drwxr-xr-x 2 rundeck root      4096 May 12 17:50 projects/
drwxr-xr-x 4 rundeck root      4096 May 12 17:50 repository/
-rw-r--r-- 1 rundeck root   7777980 May 12 17:55 rundeck-cli-1.4.2-all.jar
-rw-r--r-- 1 rundeck root 260816097 May 11 17:53 rundeck.war
drwxrwxr-x 1 rundeck root      4096 May 11 17:53 server/
-rw-r--r-- 1 rundeck root      1824 May 12 17:55 test_job.yaml
drwxrwxr-x 2 rundeck root      4096 May 11 17:53 user-assets/
drwxrwxr-x 1 rundeck root      4096 May 12 17:54 var/
rundeck@6bfe7aeae911:~$ 
rundeck@6bfe7aeae911:~$ java -jar rundeck-cli-1.4.2-all.jar jobs load --file ./test_job.yaml --project DEMO --duplicate update
Exception in thread "main" java.lang.IllegalArgumentException: Unable to create converter for class org.rundeck.client.api.model.ImportResult
    for method RundeckApi.loadJobs
	at retrofit2.Utils.methodError(Utils.java:54)
	at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:126)
	at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:85)
	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
	at com.sun.proxy.$Proxy9.loadJobs(Unknown Source)
	at org.rundeck.client.tool.commands.Jobs.lambda$load$2(Jobs.java:174)
	at org.rundeck.client.util.Client.apiCallDowngradable(Client.java:606)
	at org.rundeck.client.tool.commands.AppCommand.apiCallDowngradable(AppCommand.java:103)
	at org.rundeck.client.tool.commands.AppCommand.apiCall(AppCommand.java:74)
	at org.rundeck.client.tool.commands.Jobs.load(Jobs.java:174)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.rundeck.toolbelt.ToolBelt$MethodInvoker.run(ToolBelt.java:1030)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:619)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:471)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runCommand(ToolBelt.java:619)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.run(ToolBelt.java:471)
	at org.rundeck.toolbelt.ToolBelt$CommandSet.runMain(ToolBelt.java:428)
	at org.rundeck.client.tool.Main.main(Main.java:78)
Caused by: java.lang.IllegalArgumentException: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at retrofit2.converter.jaxb.JaxbConverterFactory.contextForType(JaxbConverterFactory.java:81)
	at retrofit2.converter.jaxb.JaxbConverterFactory.responseBodyConverter(JaxbConverterFactory.java:72)
	at org.rundeck.client.util.QualifiedTypeConverterFactory.responseBodyConverter(QualifiedTypeConverterFactory.java:58)
	at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:362)
	at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:345)
	at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:124)
	... 21 more
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:278)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:421)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
	at retrofit2.converter.jaxb.JaxbConverterFactory.contextForType(JaxbConverterFactory.java:79)
	... 26 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:122)
	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:155)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:276)
	... 30 more
rundeck@6bfe7aeae911:~$ 
rundeck@6bfe7aeae911:~$ 
rundeck@6bfe7aeae911:~$ 
```

**Comment by gschueler** [comment]
I'll look into this

**Comment by gschueler** [comment]
works ok with java 8, but not java 11 :-/

**Comment by gschueler** [comment]
@fidalcastro I'll create a new 1.4 release shortly

**Comment by fidalcastro** [comment]
@gschueler Thanks for fixing this issue. Rundeck CLI v1.4.3 works fine with Java11 + Rundeck server latest version.
