### ISSUE TITLE
RUN-2080: Errors messages on xml job import in 2.0.7

### ISSUE THREAD

**Issue by uubufr** [rundeck/rundeck-cli#538]
Hello,

I have an error message when I want to import job in xml format. This issue occur only with 2.0.7, all work fine with 2.0.6.

I can export an xml job:
java -jar rundeck-cli jobs list --project=TEST --format=xml -f test.xml

But if I import this job:
java -jar rundeck-cli jobs load --project=TEST --format=xml --duplicate=update --file=test.xml

The job is imported successfully, but I have these errors appearing:

```
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2477)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:750)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:674)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2085)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:808)
        at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:357)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2095)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1513)
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:33)
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
        at org.rundeck.client.util.Client.checkErrorDowngradable(Client.java:166)
        at org.rundeck.client.util.Client.apiCallDowngradable(Client.java:606)
        at org.rundeck.client.tool.commands.RdToolImpl.apiCallDowngradable(RdToolImpl.java:107)
        at org.rundeck.client.tool.commands.RdToolImpl.apiCall(RdToolImpl.java:78)
        at org.rundeck.client.tool.commands.Jobs.load(Jobs.java:181)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1972)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.rundeck.client.tool.Main.main(Main.java:155)
```

I use Rundeck 4.17.1, openjdk 11 and almaLinux 8.6.

Thanks

**Comment by MegaDrive68k** [comment]
Confirmed.

![Screenshot_2023-11-14_09-25-16](https://github.com/rundeck/rundeck-cli/assets/51376003/77405ab1-6258-415e-a024-a28c727e7900)

It works on 2.0.6.

**Comment by eagle-rr** [comment]
We hit similar error with Rundeck Client 2.0.7 when loading xml files too.  Reverting back to Rundeck Client 2.0.6 works fine.

**Comment by amontepaone** [comment]
Can you tell me how to revert back to Tundeck Client 2.0.6 ?
Regards
