### ISSUE TITLE
Exception running "rd" client on linux

### ISSUE THREAD

**Issue by kamalpnayan** [rundeck/rundeck-cli#86]
I can't run "rd" with jdk 8 on Red Hat Enterprise Linux Server release 6.8.

**/rundeck/rd/rd-1.0.8/bin>java -version**
java version "1.8.0-ea"
Java(TM) SE Runtime Environment (build 1.8.0-ea-b88)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b30, mixed mode)
**rundeck/rd/rd-1.0.8/bin>rd**
/usr/java/jdk1.8.0-b88/bin/java -jar /home/xxxx/rundeck/rd/rd-1.0.8/lib/rundeck-cli-1.0.8-all.jar
Exception in thread "main" java.lang.IncompatibleClassChangeError
        at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:383)
        at com.simplifyops.toolbelt.ToolBelt.add(ToolBelt.java:116)
        at org.rundeck.client.tool.Main.tool(Main.java:88)
        at org.rundeck.client.tool.Main.main(Main.java:46)
Caused by: java.lang.NoSuchMethodException: no such method: java.lang.invoke.LambdaMetafactory.metafactory(Lookup,String,MethodType,MethodType,MethodHandle,MethodType)CallSite/invokeStatic
        at java.lang.invoke.MemberName.makeAccessException(MemberName.java:758)
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:875)
        at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1037)
        at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1341)
        at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:381)
        ... 3 more
Caused by: java.lang.NoSuchMethodError: java.lang.invoke.LambdaMetafactory.metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
        at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
        at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:847)
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:872)
        ... 6 more

**Comment by gschueler** [comment]
*scratches head* It looks like you are running a Beta version of Java 1.8: `build 1.8.0-ea-b88`

can you try a release version?

**Comment by kamalpnayan** [comment]
works!
